Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2024-10, with the labels that each got.

#1164 Translations update from Kodi Weblate
  XBMC Remote/Settings.bundle/pt-br.lproj/Root.strings
  XBMC Remote/pt-br.lproj/Localizable.strings
Labels: improvement

#1148 Bugfix: Restore stronger font scaling for custom buttons
  XBMC Remote/rightCellView.xib
Labels: bugfix

#1149 Bugfix: Bring back fullscreen info screen for album/artist
  XBMC Remote/AppDelegate.m
Labels: bugfix

#1152 Bugfix: Global Search might not show ratings for movies and TV shows
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1156 Bugfix: Ensure correct cell height in heightForRowAtIndexPath
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1158 Bugfix: Fix memory leak when calculating average color
  XBMC Remote/Utilities.m
Labels: bugfix

#1160 Bugfix: Ensure proper background color for section header in case of download error
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1147 Improvement: NowPlaying info prioritizes release year when truncating
  XBMC Remote/NowPlaying.m
Labels: improvement

#1157 Improvement: Messages shall not be shown on iPhone main menu
  XBMC Remote/MasterViewController.m
Labels: improvement

#1154 Bugfix: Ensure "No items found" is not truncated
  XBMC Remote/DetailViewController.xib
  XBMC Remote/NowPlaying.xib
Labels: bugfix

#1150 Maintenance: Rework iPhone menu button implementation
  XBMC Remote/HostManagementViewController.h
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/InitialSlidingViewController.h
  XBMC Remote/InitialSlidingViewController.m
  XBMC Remote/MasterViewController.h
  XBMC Remote/MasterViewController.m
  XBMC Remote/RightMenuViewController.h
Labels: maintenance

#1151 Maintenance: Small coding style changes and internal rework
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/HostViewController.m
  XBMC Remote/MasterViewController.m
  XBMC Remote/MessagesView.m
  XBMC Remote/RightMenuViewController.m
  XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
  XBMC Remote/Utilities.m
  XBMC Remote/ViewControllerIPad.m
Labels: maintenance

#1163 Improvement: Faster connect to Kodi server
  XBMC Remote/AppDelegate.m
  XBMC Remote/InitialSlidingViewController.m
  XBMC Remote/MasterViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/ViewControllerIPad.h
  XBMC Remote/ViewControllerIPad.m
  XBMC Remote/en.lproj/Localizable.strings
  XBMC Remote/tcpJSONRPC.m
Labels: improvement

#1165 Improvement: Use max resolution and correct aspect ratio for iPhone's playlist toggle button
  XBMC Remote/NowPlaying.m
Labels: improvement

#1161 Improvement: Avoid glitches of searchbar animation when leaving iPad fullscreen
  XBMC Remote/DetailViewController.m
Labels: improvement

#1167 Feature: Support language pt-br
  Kodi Remote.xcodeproj/project.pbxproj
Labels: feature

#1153 Rework presentation of search results
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
Labels: improvement

#1162 Rework iPad stack controller
  XBMC Remote/NowPlaying.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/ViewControllerIPad.m
  XBMC Remote/iPad/MenuViewController.m
  XBMC Remote/iPad/StackScrollViewController.h
  XBMC Remote/iPad/StackScrollViewController.m
Labels: improvement, maintenance

#1169 Bugfix: Make menu button in server list work again on iPhone
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/NowPlaying.m
Labels: bugfix

#1174 Translations update from Kodi Weblate
  XBMC Remote/de.lproj/Localizable.strings
  XBMC Remote/es.lproj/Localizable.strings
  XBMC Remote/it.lproj/Localizable.strings
  XBMC Remote/ko-kr.lproj/Localizable.strings
Labels: improvement

#1171 Bugfix: Do not truncate version info on iPad
  XBMC Remote/AppInfoViewController.xib
Labels: bugfix

#1172 Improvement: Allow font scaling for MoreItemsVC
  XBMC Remote/MoreItemsViewController.m
Labels: improvement

#1128 Improvement: Remove confirmation of power menu actions
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/RemoteController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
  XBMC Remote/ViewControllerIPad.m
Labels: improvement

#1168 Maintenance: Coding style for enums
  XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/ECSlidingViewController/ECSlidingViewController.h
  XBMC Remote/NowPlaying.m
  XBMC Remote/RemoteController.h
  XBMC Remote/RemoteController.m
  XBMC Remote/SettingsValuesViewController.h
  XBMC Remote/SettingsValuesViewController.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
  XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.h
  XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPCError.h
  XBMC Remote/mainMenu.h
Labels: maintenance

#1170 Fixes for connection issues after wakeup
  XBMC Remote/InitialSlidingViewController.m
  XBMC Remote/tcpJSONRPC.m
Labels: bugfix

#1177 Bugfix: Apply rounded edges to grid view thumb's bottom
  XBMC Remote/PosterCell.m
Labels: bugfix

#1173 Maintenance: Use long type for database IDs
  XBMC Remote/DetailViewController.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/RemoteController.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
  XBMC Remote/XBMCVirtualKeyboard.m
Labels: maintenance
