Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2024-11, with the labels that each got.

#1187 Translations update from Kodi Weblate
  XBMC Remote/cs.lproj/Localizable.strings
Labels: improvement

#1041 Maintenance: Remove isViewDidLoad, rework iPad corner info and detail view
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/DetailViewController.xib
  XBMC Remote/ShowInfoViewController.h
  XBMC Remote/ShowInfoViewController.m
Labels: maintenance

#1180 Bugfix: Show menu icon on iPhone server list after launch
  XBMC Remote/HostManagementViewController.m
Labels: bugfix

#1185 Bugfix: restore GlobalSearch sort method and sort order
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1181 Improvement: Add timers to RunLoopCommonModes to avoid blockage by dragging a view
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/MessagesView.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/tcpJSONRPC.m
Labels: improvement

#1184 Improvement: Simplified actionsheet title for playlist items
  XBMC Remote/NowPlaying.m
Labels: improvement

#1186 Rework image cache
  XBMC Remote/ConvenienceMacros.h
  XBMC Remote/NowPlaying.m
  XBMC Remote/SDWebImage/SDImageCache.m
  XBMC Remote/SDWebImage/SDWebImageDecoder.m
  XBMC Remote/SDWebImage/SDWebImageDownloader.m
  XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.m
  XBMC Remote/SDWebImage/UIImageView+WebCache.m
  XBMC Remote/UIImage+Resize/UIImage+Resize.h
  XBMC Remote/UIImage+Resize/UIImage+Resize.m
  XBMC Remote/Utilities.m
Labels: improvement

#1182 Rework wakeup of tcpJSONRPC
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.m
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/MasterViewController.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/ViewControllerIPad.m
  XBMC Remote/VolumeSliderView.m
  XBMC Remote/tcpJSONRPC.m
Labels: improvement

#1183 Rework handling default server port and tcp port
  XBMC Remote/AppDelegate.m
  XBMC Remote/ConvenienceMacros.h
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/HostViewController.m
  XBMC Remote/HostViewController.xib
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
  XBMC Remote/tcpJSONRPC.m
Labels: improvement, maintenance

#1189 Bugfix: avoid visual glitch on iPad when closing stack while bounce animation is active
  XBMC Remote/iPad/StackScrollViewController.m
Labels: bugfix

#1190 Bugfix: iPad stack not movable after leaving fullscreen with toolbar's nowplaying button
  XBMC Remote/iPad/StackScrollViewController.m
Labels: bugfix

#1192 Bugfix: use correct default thumbs for recordings and timers in grid view
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1193 Maintenance: clean up dealloc
  XBMC Remote/DetailViewController.m
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/HostViewController.m
  XBMC Remote/MasterViewController.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/RemoteController.m
  XBMC Remote/RightMenuViewController.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/ViewControllerIPad.m
  XBMC Remote/VolumeSliderView.m
  XBMC Remote/XBMCVirtualKeyboard.m
  XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
  XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPCError.m
  XBMC Remote/iPad/StackScrollViewController.m
  XBMC Remote/tcpJSONRPC.m
Labels: maintenance

#1191 Rework PosterCell and RecentlyAddedCell
  XBMC Remote/ConvenienceMacros.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/PosterCell.h
  XBMC Remote/PosterCell.m
  XBMC Remote/RecentlyAddedCell.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
Labels: bugfix, improvement, maintenance

#1194 Bugfix: do not have "rounded corners" always on for "recently added" grid view
  XBMC Remote/DetailViewController.m
  XBMC Remote/Utilities.h
Labels: bugfix

#1196 Bugfix: GlobalSearch by type respects user sort order for section during search
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1195 Rework RecentlyAddedCell and PosterCell
  XBMC Remote/DetailViewController.m
  XBMC Remote/PosterCell.m
  XBMC Remote/RecentlyAddedCell.h
  XBMC Remote/RecentlyAddedCell.m
Labels: bugfix, improvement, maintenance
