Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2024-09, with the labels that each got.

#1121 Bugfix: Restore fix for vertical pos of custom button view
  XBMC Remote/RightMenuViewController.m
Labels: bugfix

#1112 Bugfix: calculate correct height of labels when using auto-layout
  XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
  XBMC Remote/Utilities.m
Labels: bugfix

#1113 Bugfix: correct iPad stack bounce behaviour after fullscreen
  XBMC Remote/iPad/StackScrollViewController.m
Labels: bugfix

#1115 Bugfix: entering addons via Music/Movies/Videos/TVShows menus
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1117 Bugfix: show correct title in Settings menu
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1118 Bugfix: set speed via longpress NowPlaying's seek buttons
  XBMC Remote/NowPlaying.xib
Labels: bugfix

#1119 Bugfix: another workaround to make list view scrollbars visible for iOS17
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1097 Review and rework menu config
  XBMC Remote/AppDelegate.h
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.m
Labels: improvement, maintenance

#1103 Only show embedded trailer for youtube links
  XBMC Remote/ShowInfoViewController.m
Labels: improvement

#1120 Improvement: consistently enter full screen remote when tapping remote button (iPhone)
  XBMC Remote/NowPlaying.m
Labels: improvement

#1114 Improvement: allow toolbar buttons while active search
  XBMC Remote/DetailViewController.m
Labels: improvement

#1096 Support "Play using..." to allow playback to an UPnP device
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.m
  XBMC Remote/NowPlaying.h
  XBMC Remote/NowPlaying.m
  XBMC Remote/NowPlaying.xib
  XBMC Remote/VersionCheck.h
  XBMC Remote/VersionCheck.m
  XBMC Remote/en.lproj/Localizable.strings
Labels: feature

#1084 Improvement: limit font scaling for more consistent look
  XBMC Remote/AppInfoViewController.xib
  XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
  XBMC Remote/ConvenienceMacros.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/DetailViewController.xib
  XBMC Remote/HostManagementViewController.xib
  XBMC Remote/HostViewController.xib
  XBMC Remote/MessagesView.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/PosterCell.m
  XBMC Remote/ProgressPieView.m
  XBMC Remote/RecentlyAddedCell.m
  XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
  XBMC Remote/SettingsValuesViewController.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/ShowInfoViewController.xib
  XBMC Remote/ViewControllerIPad.m
  XBMC Remote/VolumeSliderView.xib
  XBMC Remote/cellView.xib
  XBMC Remote/jsonDataCell.xib
  XBMC Remote/playlistCellView.xib
  XBMC Remote/rightCellView.xib
  XBMC Remote/serverListCellView.xib
Labels: improvement

#1104 Improve playlist user experience
  XBMC Remote/NowPlaying.h
  XBMC Remote/NowPlaying.m
Labels: improvement

#1122 No need to invalidate timers in dealloc
  XBMC Remote/NowPlaying.m
  XBMC Remote/VolumeSliderView.m
Labels: maintenance

#1107 Feature: Queue and Play a season via longpress menu
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
Labels: improvement, feature

#1090 Rework overlay and season
  XBMC Remote/DetailViewController.m
Labels: improvement, maintenance

#1109 Rework messages to centralized approach
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/HostManagementViewController.h
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/MasterViewController.h
  XBMC Remote/MasterViewController.m
  XBMC Remote/NowPlaying.h
  XBMC Remote/NowPlaying.m
  XBMC Remote/RemoteController.h
  XBMC Remote/RemoteController.m
  XBMC Remote/RightMenuViewController.h
  XBMC Remote/RightMenuViewController.m
  XBMC Remote/SettingsValuesViewController.h
  XBMC Remote/SettingsValuesViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
  XBMC Remote/ViewControllerIPad.m
Labels: bugfix, maintenance

#1126 Translations update from Kodi Weblate
  XBMC Remote/de.lproj/Localizable.strings
  XBMC Remote/es.lproj/Localizable.strings
  XBMC Remote/it.lproj/Localizable.strings
Labels: improvement

#1125 Bugfix: avoid showing messages aligned with action sheets on iPhone
  XBMC Remote/MasterViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
Labels: bugfix

#1135 Bugfix: Show movie duration of 3-digit minutes properly in playlist
  XBMC Remote/playlistCellView.xib
Labels: bugfix

#1136 Bugfix: Roating and leaving iPad fanart fullscreen
  XBMC Remote/iPad/StackScrollViewController.m
Labels: bugfix

#1140 Bugfix: Add missing icon for movie tags
  XBMC Remote/AppDelegate.m
  XBMC Remote/Images.xcassets/icons/toolbar/st_movie_tags.imageset/Contents.json
  XBMC Remote/Images.xcassets/icons/toolbar/st_movie_tags.imageset/st_movie_tags.png
  XBMC Remote/Images.xcassets/icons/toolbar/st_movie_tags.imageset/st_movie_tags@2x.png
Labels: bugfix

#1141 Bugfix: Present action sheet with UPnP players from correct origin (iPad)
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1142 Bugfix: Avoid scroll up arrow to be shortly visible on iPad's detail info screen
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/ShowInfoViewController.xib
Labels: bugfix

#1143 Bugfix: Keep exit fullscreen button always reachable in iPad fullscreen
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1146 Bugfix: Error or no results when selecting an item from filtered list
  XBMC Remote/DetailViewController.m
  XBMC Remote/mainMenu.h
  XBMC Remote/mainMenu.m
Labels: bugfix

#1144 Rework animations and content of iPad corner info
  XBMC Remote/DetailViewController.m
Labels: bugfix, improvement

#1139 Maintenance: Handle type check inside the time conversion helper
  XBMC Remote/NowPlaying.m
  XBMC Remote/Utilities.m
Labels: maintenance

#1138 Maintenance: activeLayoutView shall use UTableView type
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
Labels: maintenance

#1145 Maintenance: Rework AppDelegate to use appropriate types
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
Labels: maintenance
