Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2024-08, with the labels that each got.

#1095 Translations update from Kodi Weblate
  XBMC Remote/Settings.bundle/ast-es.lproj/Root.strings
  XBMC Remote/Settings.bundle/ca-es.lproj/Root.strings
  XBMC Remote/ast-es.lproj/Localizable.strings
  XBMC Remote/ca-es.lproj/Localizable.strings
Labels: improvement

#1100 Remove obsolete files from bundle and redo bundle
  Kodi Remote.xcodeproj/project.pbxproj
  XBMC Remote/Kodi Remote-Info.plist
  XBMC Remote/fonts/DejaVuSans-Bold-Caps.ttf
  XBMC Remote/sign.mp3
Labels: maintenance

#1099 Bugfix: Use same message dimension for remote and custom button screen
  XBMC Remote/RightMenuViewController.m
Labels: bugfix

#1088 Bugfix: Embedded remote needs transparent background
  XBMC Remote/RightMenuViewController.m
Labels: bugfix

#1093 Let NowPlaying handle entering background
  XBMC Remote/NowPlaying.m
Labels: bugfix

#1098 Bugfix: Resolve never ending Global Search animation
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1089 Improvement and fixes for channel and recording lists
  XBMC Remote/DetailViewController.m
Labels: bugfix, improvement

#1085 Redo party mode button in playlist toolbar
  XBMC Remote/Images.xcassets/buttons/button_party_off.imageset/button_party_off.png
  XBMC Remote/Images.xcassets/buttons/button_party_off.imageset/button_party_off@2x.png
  XBMC Remote/Images.xcassets/buttons/button_party_on.imageset/button_party_on.png
  XBMC Remote/Images.xcassets/buttons/button_party_on.imageset/button_party_on@2x.png
  XBMC Remote/NowPlaying.m
  XBMC Remote/NowPlaying.xib
Labels: bugfix

#1094 Rework settings grid view and animation when changing tabs
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.m
Labels: bugfix, improvement, maintenance

#1081 Improvement: Handle longpress for sources and support play/queue
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.m
Labels: improvement, feature

#1083 Improvement: Global Search support for cast, plot and tagline
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
Labels: improvement, feature

#1082 Maintenance: assigned value was never used (Xcode analyzer warning)
  XBMC Remote/VolumeSliderView.m
Labels: maintenance

#1091 Rework virtual keyboard
  XBMC Remote/XBMCVirtualKeyboard.h
  XBMC Remote/XBMCVirtualKeyboard.m
Labels: improvement, maintenance

#1092 Rework RemoteController key handling
  XBMC Remote/RemoteController.h
  XBMC Remote/RemoteController.m
  XBMC Remote/VersionCheck.h
  XBMC Remote/VersionCheck.m
Labels: improvement, maintenance

#1087 Rework SettingsValuesViewController
  XBMC Remote/Images.xcassets/ui_elements/tableDown.imageset/Contents.json
  XBMC Remote/Images.xcassets/ui_elements/tableDown.imageset/tableDown.png
  XBMC Remote/Images.xcassets/ui_elements/tableDown.imageset/tableDown@2x.png
  XBMC Remote/Images.xcassets/ui_elements/tableUp.imageset/Contents.json
  XBMC Remote/Images.xcassets/ui_elements/tableUp.imageset/tableUp.png
  XBMC Remote/Images.xcassets/ui_elements/tableUp.imageset/tableUp@2x.png
  XBMC Remote/SettingsValuesViewController.h
  XBMC Remote/SettingsValuesViewController.m
Labels: improvement, maintenance

#1077 Improve performance when starting slideshows and updating huge playlists
  XBMC Remote/DetailViewController.m
  XBMC Remote/Images.xcassets/icons/source/mjpeg.imageset/Contents.json
  XBMC Remote/Images.xcassets/icons/source/mjpeg.imageset/mjpeg.png
  XBMC Remote/NowPlaying.h
  XBMC Remote/NowPlaying.m
  XBMC Remote/RemoteController.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
Labels: improvement
