Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2025-05, with the labels that each got.

#1263 Translations update from Kodi Weblate
  XBMC Remote/Settings.bundle/id-id.lproj/Root.strings
  XBMC Remote/Settings.bundle/sv.lproj/Root.strings
  XBMC Remote/id-id.lproj/Localizable.strings
  XBMC Remote/sv.lproj/InfoPlist.strings
  XBMC Remote/sv.lproj/Localizable.strings
Labels: improvement

#1266 Feature: Add support for Indonesian (id-id)
  Kodi Remote.xcodeproj/project.pbxproj
Labels: feature

#1259 Improvement: Use both album and artist for Wikipedia search
  XBMC Remote/DetailViewController.m
Labels: improvement

#1255 Rework volume change
  XBMC Remote/VolumeSliderView.m
Labels: improvement

#1256 Remove blackTableSeparator special handling
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.m
  XBMC Remote/ShowInfoViewController.m
Labels: maintenance

#1258 Improvement: Show Remote App memory usage and image cache size
  XBMC Remote/HostManagementViewController.h
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
Labels: improvement

#1254 Feature: Share URL of item
  Kodi Remote.xcodeproj/project.pbxproj
  XBMC Remote/DetailViewController.m
  XBMC Remote/SharingActivityItemSource/SharingActivityItemSource.h
  XBMC Remote/SharingActivityItemSource/SharingActivityItemSource.m
  XBMC Remote/en.lproj/Localizable.strings
Labels: feature

#1253 Maintenance: Coding style changes
  XBMC Remote/AppDelegate.h
  XBMC Remote/AppDelegate.m
  XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
  XBMC Remote/DetailViewController.m
  XBMC Remote/GlobalData.h
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/HostViewController.m
  XBMC Remote/InitialSlidingViewController.m
  XBMC Remote/KenBurns/JBKenBurnsView.h
  XBMC Remote/MasterViewController.m
  XBMC Remote/MoreItemsViewController.m
  XBMC Remote/NowPlaying.h
  XBMC Remote/NowPlaying.m
  XBMC Remote/OBShapedButton/OBShapedButton.h
  XBMC Remote/OBShapedButton/OBShapedButton.m
  XBMC Remote/OBShapedButton/UIImage+ColorAtPixel.m
  XBMC Remote/OBSlider/OBSlider.h
  XBMC Remote/OBSlider/OBSlider.m
  XBMC Remote/RemoteController.h
  XBMC Remote/RemoteController.m
  XBMC Remote/RightMenuViewController.m
  XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.h
  XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
  XBMC Remote/SettingsValuesViewController.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/ViewControllerIPad.h
  XBMC Remote/ViewControllerIPad.m
  XBMC Remote/VolumeSliderView.h
  XBMC Remote/VolumeSliderView.m
  XBMC Remote/XBMCVirtualKeyboard.m
  XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.h
  XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
  XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPCError.h
  XBMC Remote/iPad/MenuViewController.h
  XBMC Remote/iPad/MenuViewController.m
  XBMC Remote/iPad/StackScrollViewController.h
  XBMC Remote/iPad/StackScrollViewController.m
  XBMC Remote/mainMenu.m
  XBMC Remote/tcpJSONRPC.m
Labels: maintenance

#1257 Show "clearing cache" popover at least for two seconds
  XBMC Remote/MasterViewController.m
  XBMC Remote/ViewControllerIPad.m
Labels: improvement

#1273 Translations update from Kodi Weblate
  XBMC Remote/de.lproj/Localizable.strings
  XBMC Remote/es.lproj/Localizable.strings
  XBMC Remote/pl.lproj/Localizable.strings
  XBMC Remote/sv.lproj/Localizable.strings
Labels: improvement

#1279 Translations update from Kodi Weblate
  XBMC Remote/Settings.bundle/zh-Hans.lproj/Root.strings
  XBMC Remote/fi-fi.lproj/Localizable.strings
  XBMC Remote/id-id.lproj/Localizable.strings
  XBMC Remote/it.lproj/Localizable.strings
  XBMC Remote/ko-kr.lproj/Localizable.strings
  XBMC Remote/zh-Hans.lproj/Localizable.strings
Labels: improvement

#1280 Maintenance: Rework building action sheets
  XBMC Remote/DetailViewController.m
Labels: bugfix, maintenance
