Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2025-07, with the labels that each got.

#1285 Translations update from Kodi Weblate
  XBMC Remote/Settings.bundle/de.lproj/Root.strings
  XBMC Remote/Settings.bundle/es-es.lproj/Root.strings
  XBMC Remote/Settings.bundle/id-id.lproj/Root.strings
  XBMC Remote/Settings.bundle/it.lproj/Root.strings
  XBMC Remote/Settings.bundle/ko-kr.lproj/Root.strings
  XBMC Remote/Settings.bundle/pl.lproj/Root.strings
  XBMC Remote/Settings.bundle/sv.lproj/Root.strings
  XBMC Remote/Settings.bundle/zh-Hans.lproj/Root.strings
  XBMC Remote/de.lproj/Localizable.strings
  XBMC Remote/es.lproj/Localizable.strings
  XBMC Remote/id-id.lproj/Localizable.strings
  XBMC Remote/it.lproj/Localizable.strings
  XBMC Remote/ko-kr.lproj/Localizable.strings
  XBMC Remote/pl.lproj/Localizable.strings
  XBMC Remote/sv.lproj/Localizable.strings
  XBMC Remote/zh-Hans.lproj/Localizable.strings
Labels: improvement

#1294 Bugfix: NowPlaying dimensions potentially wrong after entering from library view
  XBMC Remote/DetailViewController.m
  XBMC Remote/NowPlaying.m
Labels: bugfix

#1291 Improvement: Small rework related to iPad corner info
  XBMC Remote/DetailViewController.m
Labels: improvement

#1289 Maintenance: Cleanup obsolete framework methods
  XBMC Remote/ActorCell.m
  XBMC Remote/AppInfoViewController.m
  XBMC Remote/CustomNavigationController.m
  XBMC Remote/DetailViewController.m
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/InitialSlidingViewController.m
  XBMC Remote/MasterViewController.m
  XBMC Remote/MoreItemsViewController.m
  XBMC Remote/RightMenuViewController.m
  XBMC Remote/SettingsValuesViewController.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/iPad/MenuViewController.m
  XBMC Remote/iPad/StackScrollViewController.m
  XBMC Remote/jsonDataCell.m
Labels: maintenance

#1293 Code clean up and some rework
  XBMC Remote/ActorCell.h
  XBMC Remote/ActorCell.m
  XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
  XBMC Remote/DetailViewController.m
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/PosterCell.m
  XBMC Remote/PosterHeaderView.m
  XBMC Remote/RecentlyAddedCell.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/ViewControllerIPad.m
  XBMC Remote/iPad/StackScrollViewController.m
Labels: improvement, maintenance

#1288 Maintenance: Introduce a base class for the iPhone and iPad main controller
  Kodi Remote.xcodeproj/project.pbxproj
  XBMC Remote/BaseMasterViewController.h
  XBMC Remote/BaseMasterViewController.m
  XBMC Remote/MasterViewController.h
  XBMC Remote/MasterViewController.m
  XBMC Remote/ViewControllerIPad.h
  XBMC Remote/ViewControllerIPad.m
Labels: bugfix, maintenance
