Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2025-08, with the labels that each got.

#1301 Translations update from Kodi Weblate
  XBMC Remote/Settings.bundle/gl-es.lproj/Root.strings
  XBMC Remote/Settings.bundle/uk-ua.lproj/Root.strings
  XBMC Remote/gl-es.lproj/Localizable.strings
  XBMC Remote/it.lproj/InfoPlist.strings
  XBMC Remote/pt-br.lproj/Localizable.strings
  XBMC Remote/uk-ua.lproj/InfoPlist.strings
  XBMC Remote/uk-ua.lproj/Localizable.strings
Labels: improvement

#1300 Maintenance: Refactor FloatingHeaderFlowLayout and use enums for edgesForExtendedLayout
  XBMC Remote/AppInfoViewController.m
  XBMC Remote/FloatingHeaderFlowLayout.m
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/HostViewController.m
  XBMC Remote/RemoteController.m
Labels: maintenance

#1299 Improvement: Use frosted glass effect for toolbars
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/DetailViewController.xib
  XBMC Remote/HostManagementViewController.h
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/HostManagementViewController.xib
  XBMC Remote/RightMenuViewController.m
  XBMC Remote/ShowInfoViewController.m
Labels: improvement

#1304 Release Notes 1.18
  fastlane/metadata/en-US/release_notes.txt
Labels: maintenance

#1308 Bugfix: Fix server list / search views for iPhones with wide screen
  XBMC Remote/HostViewController.m
  XBMC Remote/HostViewController.xib
  XBMC Remote/InitialSlidingViewController.m
  XBMC Remote/InitialSlidingViewController.xib
Labels: bugfix

#1311 1.18.1 hotfix for iOS 12
  Kodi Remote.xcodeproj/project.pbxproj
  fastlane/metadata/en-US/release_notes.txt
Labels: bugfix
