Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2025-03, with the labels that each got.

#1251 Translations update from Kodi Weblate
  XBMC Remote/ko-kr.lproj/Localizable.strings
Labels: improvement

#1252 Bugfix: Early return to avoid crash in inet_pton
  XBMC Remote/Utilities.m
Labels: bugfix

#1244 Release Notes 1.17
  fastlane/metadata/en-US/release_notes.txt
Labels: maintenance
