Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2025-01, with the labels that each got.

#1224 Translations update from Kodi Weblate
  XBMC Remote/Settings.bundle/af-za.lproj/Root.strings
  XBMC Remote/af-za.lproj/InfoPlist.strings
  XBMC Remote/af-za.lproj/Localizable.strings
Labels: improvement

#1216 Bugfix: Hide resume option for Kodi 11 or earlier
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/VersionCheck.h
  XBMC Remote/VersionCheck.m
Labels: bugfix

#1219 Bugfix: Fix Broadcast Details while recording is active
  XBMC Remote/ShowInfoViewController.m
Labels: bugfix

#1221 Bugfix: Use exact Kodi blue color in sRGB color space
  XBMC Remote/Utilities.m
Labels: bugfix

#1222 Bugfix: Fix crash after scrolling playlist
  XBMC Remote/NowPlaying.m
Labels: bugfix

#1225 Bugfix: Kodi icon might not reflect disconnected state on iPhone
  XBMC Remote/MasterViewController.m
Labels: bugfix

#1228 Bugfix: Properly end "Play using..." action sheet
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1227 Improvement: Party Mode icon to use Kodi blue
  XBMC Remote/Images.xcassets/buttons/button_party_on.imageset/button_party_on.png
  XBMC Remote/Images.xcassets/buttons/button_party_on.imageset/button_party_on@2x.png
Labels: improvement

#1223 Bugfix: Avoid potential crash in "Play using..."
  XBMC Remote/DetailViewController.m
Labels: bugfix

#1220 Improvement: Update progress and recording indicators for Live TV and Radio
  Kodi Remote.xcodeproj/project.pbxproj
  XBMC Remote/BroadcastProgressView.h
  XBMC Remote/BroadcastProgressView.m
  XBMC Remote/DetailViewController.m
  XBMC Remote/ProgressBarView.h
  XBMC Remote/ProgressBarView.m
  XBMC Remote/ProgressPieView.h
  XBMC Remote/ProgressPieView.m
Labels: improvement

#1233 Translations update from Kodi Weblate
  XBMC Remote/af-za.lproj/Localizable.strings
  XBMC Remote/de.lproj/Localizable.strings
  XBMC Remote/eo.lproj/Localizable.strings
  XBMC Remote/es.lproj/Localizable.strings
  XBMC Remote/pl.lproj/Localizable.strings
Labels: improvement

#1206 Maintenance: Simplify colorizeImage:withColor:
  XBMC Remote/Utilities.m
Labels: maintenance

#1217 Maintenance: Remove non needed ivars and properties in iPhone MasterVC
  XBMC Remote/MasterViewController.h
  XBMC Remote/MasterViewController.m
  XBMC Remote/RemoteController.h
Labels: maintenance

#1226 Improvement: Rework playlist progressbar
  Kodi Remote.xcodeproj/project.pbxproj
  XBMC Remote/Images.xcassets/nowplaying/pgbar_act.imageset/Contents.json
  XBMC Remote/Images.xcassets/nowplaying/pgbar_act.imageset/pgbar_act.png
  XBMC Remote/Images.xcassets/nowplaying/pgbar_act.imageset/pgbar_act@2x.png
  XBMC Remote/Images.xcassets/nowplaying/pgbar_inact_fake.imageset/Contents.json
  XBMC Remote/Images.xcassets/nowplaying/pgbar_inact_fake.imageset/pgbar_inact_fake.png
  XBMC Remote/Images.xcassets/nowplaying/pgbar_inact_fake.imageset/pgbar_inact_fake@2x.png
  XBMC Remote/Images.xcassets/ui_elements/timeBackground.imageset/Contents.json
  XBMC Remote/Images.xcassets/ui_elements/timeBackground.imageset/timeBackground.png
  XBMC Remote/NowPlaying.m
  XBMC Remote/PlaylistProgressView.h
  XBMC Remote/PlaylistProgressView.m
  XBMC Remote/playlistCellView.xib
Labels: improvement, maintenance

#1211 Maintenance: Small refactoring in DetailVC
  XBMC Remote/DetailViewController.m
  XBMC Remote/NowPlaying.m
Labels: maintenance

#1208 Maintenance: Coding style changes
  XBMC Remote/AppDelegate.m
  XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/ECSlidingViewController/ECSlidingViewController.m
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/KenBurns/JBKenBurnsView.m
  XBMC Remote/MessagesView.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/PosterCell.m
  XBMC Remote/RecentlyAddedCell.m
  XBMC Remote/RemoteController.m
  XBMC Remote/RightMenuViewController.m
  XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
  XBMC Remote/SettingsValuesViewController.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/Utilities.m
  XBMC Remote/ViewControllerIPad.m
  XBMC Remote/iPad/StackScrollViewController.m
Labels: maintenance

#1229 Feature: Support language af-za
  Kodi Remote.xcodeproj/project.pbxproj
Labels: improvement, feature

#1207 Rework handling of active tab
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/NowPlaying.h
  XBMC Remote/NowPlaying.m
  XBMC Remote/ShowInfoViewController.h
  XBMC Remote/ShowInfoViewController.m
Labels: bugfix, maintenance

#1235 Translations update from Kodi Weblate
  XBMC Remote/fi-fi.lproj/Localizable.strings
Labels: improvement

#1234 Bugfix: Update playlist after coming back from full screen remote on iPhone
  XBMC Remote/NowPlaying.m
Labels: bugfix

#1238 Bugfix: Remove local cache for PVR recordings
  XBMC Remote/AppDelegate.m
Labels: bugfix
