Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2025-09, with the labels that each got.

#1321 Translations update from Kodi Weblate
  XBMC Remote/Settings.bundle/ru-ru.lproj/Root.strings
  XBMC Remote/bs-ba.lproj/Localizable.strings
  XBMC Remote/ru-ru.lproj/Localizable.strings
Labels: improvement

#1310 Improvement: Do not continue re-connect after quit/shutdown/hibernate/suspend
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/Utilities.h
  XBMC Remote/Utilities.m
Labels: improvement

#1317 Improvement: Use full width for server name and IP / host name
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/serverListCellView.xib
Labels: improvement

#1324 Improvement: Ensure that custom buttons show icons
  XBMC Remote/DetailViewController.m
  XBMC Remote/RightMenuViewController.m
  XBMC Remote/SettingsValuesViewController.m
Labels: improvement

#1316 Maintenance: Migrate to performBatchUpdates
  XBMC Remote/DetailViewController.m
  XBMC Remote/HostManagementViewController.m
  XBMC Remote/NowPlaying.m
  XBMC Remote/RightMenuViewController.m
Labels: maintenance

#1320 Rework settings layout for iPad and some iOS versions
  XBMC Remote/SettingsValuesViewController.m
Labels: bugfix, improvement

#1328 Translations update from Kodi Weblate
  XBMC Remote/Settings.bundle/ru-ru.lproj/Root.strings
  XBMC Remote/ru-ru.lproj/Localizable.strings
Labels: improvement
