Repository xbmc/Official-Kodi-Remote-iOS, pull requests merged in 2025-02, with the labels that each got.

#1243 Translations update from Kodi Weblate
  XBMC Remote/pt-br.lproj/Localizable.strings
  XBMC Remote/ro-ro.lproj/Localizable.strings
Labels: improvement

#1240 Bugfix: Avoid crash in roundedCornerImage
  XBMC Remote/Utilities.m
Labels: bugfix

#1246 Maintenance: Correct type from NSArray to NSDictionary
  XBMC Remote/AppDelegate.m
Labels: maintenance

#1232 Maintenance: Remove unused string from localization
  XBMC Remote/NowPlaying.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/en.lproj/Localizable.strings
Labels: bugfix, maintenance

#1215 Maintenance: Rework playback to use Player.Open
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.m
  XBMC Remote/ShowInfoViewController.m
Labels: improvement, maintenance

#1237 Rework strategy to select/deselect items
  XBMC Remote/DetailViewController.m
  XBMC Remote/iPad/StackScrollViewController.m
Labels: improvement

#1241 Maintenance: Coding styles and minor refactoring
  XBMC Remote/AppDelegate.m
  XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
  XBMC Remote/DetailViewController.h
  XBMC Remote/DetailViewController.m
  XBMC Remote/HostViewController.m
  XBMC Remote/KenBurns/JBKenBurnsView.m
  XBMC Remote/MasterViewController.m
  XBMC Remote/MoreItemsViewController.m
  XBMC Remote/NowPlaying.h
  XBMC Remote/NowPlaying.m
  XBMC Remote/RemoteController.m
  XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
  XBMC Remote/ShowInfoViewController.m
  XBMC Remote/Utilities.m
  XBMC Remote/ViewControllerIPad.m
  XBMC Remote/VolumeSliderView.m
  XBMC Remote/iPad/StackScrollViewController.m
  XBMC Remote/tcpJSONRPC.m
Labels: maintenance

#1248 Play TV/Radio channels on selection
  XBMC Remote/AppDelegate.m
  XBMC Remote/DetailViewController.m
Labels: improvement, maintenance

#1250 Music playlist items shall only show song title and artist
  XBMC Remote/NowPlaying.m
Labels: improvement
